[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
ephemeral_vault = "11111111111111111111111111111111"

[programs.devnet]
ephemeral_vault = "11111111111111111111111111111111"

[programs.mainnet]
ephemeral_vault = "11111111111111111111111111111111"

[registry]
url = "https://api.github.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --lib"
